#!/usr/bin/env node

var express = require('express');
var http = require('http')
var path = require('path');
var fs = require('fs');
var async = require('async');
var _ = require('underscore');
var crypto = require('crypto');
var MobileDetect = require('mobile-detect');
var config = require('./config');
var mosaic = require('./mosaic');
var mongobase = require('./mongobase');
var utils = require('./utils');
var twitimage = require('./twitimage');

var ROOTDIR = path.join(__dirname, config.mosaic.folders.root);

var app = express();

app.configure(function(){
	app.set('port', process.env.PORT || 3000);
	app.set('views', __dirname + '/views');
	app.set('view engine', 'jade');
	app.use(express.favicon());
	if(config.showExpressDebugInfo) app.use(express.logger('tiny'));
	app.use(express.bodyParser());
	app.use(express.methodOverride());
	app.use(express.cookieParser('kerstkaart2013bbbbb4645sf6s4fs'));
	app.use(express.session());
	app.use(app.router);
	app.use(require('stylus').middleware(__dirname + '/public'));
	app.use(express.static(path.join(__dirname, 'public')));
});

app.configure('development', function(){
	app.use(express.errorHandler());
});

http.createServer(app).listen(app.get('port'), function(){
	console.log("Express server listening on port " + app.get('port'));
});

app.get('/fancybg', function (req, res){
	mongobase.getAllTilesWithTitle(function (err, fulltiles) {
		if(err) return utils.sendError(err, res);

		var tiles = _.map(fulltiles, function (tile){
			return {
				title: tile.title,
				image: '/mosaic/' + tile.tileflying
			};
		});

		tiles = _.shuffle(tiles); //shuffle the tiles

		tiles = tiles.slice(0, 40); // limit to 50 tiles everywhere

		if( isMobile(req) ){
			if(config.showDebugInfo) console.log('its a mobile');
			tiles = tiles.slice(0, 16); // limit to 20 tiles on mobile
		}

		res.render('fancybg', {
			title: 'background | MiX Kerstkaart 2013',
			tiles: tiles,
			mobile: isMobile(req)
		});
	})
});

app.get('/', function (req, res){
	renderView(req, res, true, isMobile(req), false);  // put the first boolean back on 'true' if your really want the fancy bg
});

app.get('/simple', function (req, res){
	renderView(req, res, false, isMobile(req), false);
});

// force mobile (for testing purposes):
app.get('/mobile', function (req, res){
	renderView(req, res, false, true, false);
});

// force oldfashion upload (for testing purposes):
app.get('/oldfashionupload', function (req, res) {
	renderView(req, res, false, isMobile(req), true);
});

// force desktop
app.get('/desktop', function (req, res) {
	renderView(req, res, false, false, false);
});


function renderView(req, res, fancybg, mobile, forceOldFashionUpload, userid){
	getSomeRandomTilesWithPosition(50, function (err, tiles) {
		if(err) return utils.sendError(err, res);

		res.render('index', {
			title: '| MiX Kerstkaart 2013',
			tiles: tiles,
			card : {
				width: config.mosaic.greetingcard.lowres.width,
				height: config.mosaic.greetingcard.lowres.height,
				mosaicOffsetX: config.mosaic.greetingcard.lowres.offset.x,
				mosaicOffsetY: config.mosaic.greetingcard.lowres.offset.y
			},
			fancybg: fancybg,
			mobile: mobile,
			forceOldFashionUpload: forceOldFashionUpload,
			userid: userid
		});
	});
}



app.post('/xhrupload', function (req, res){
	if(!req.xhr) return utils.sendError(new Error('got no xhr request'), res);

	var size = req.header('x-file-size');
	var type = req.header('x-file-type');
	var name = path.basename(req.header('x-file-name'));


	//name = crypto.createHash('md5').update( ''+(Date.now()) ).digest('hex') + '_' + name;
	name = (Date.now()) + '_' + (utils.removeFileExt(name)).substr(0,6) + path.extname(name) ;
	var uploadedFile = path.join(ROOTDIR, config.mosaic.folders.main, name);

	var ws = fs.createWriteStream( uploadedFile );

	req.on('data', function (data) {
		ws.write(data);
	});

	req.on('end', function () {
		if(config.showDebugInfo) console.log("XHR Upload done");
		ws.end();
		renderMosaic(null, uploadedFile, req, res);
	});
});

app.post('/oldfashionupload', function (req, res) {
	if(!req.files.file) return renderView(req, res, false, false); // just render the normal page


	var name = req.files.file.name;

	name = (Date.now()) + '_' + (utils.removeFileExt(name)).substr(0,6) + path.extname(name) ;
	var uploadedFile = path.join(ROOTDIR, config.mosaic.folders.main, name);

	fs.rename(req.files.file.path, uploadedFile, function (err) {
		if(err) return utils.sendError(err, res);

		var user = {
			userimage: uploadedFile,
		};

		mongobase.saveUser(user, function (err, user) {
			if(err) return utils.sendError(err, res);

			// dont render now, this is an old fashion upload: the browser is loading the page again

			// send user id (generated by DB) back to browser so it can request the creation of its mosaic:
			renderView(req, res, false, false, true, user._id);
		});
	});
});

app.post('/api/startrender', function (req, res) {
	if(!req.body.userid) return utils.sendError(new Error('got no user id'), res);

	mongobase.getUser( req.body.userid, function (err, user) {
		if(err) return utils.sendError(err, res);

		renderMosaic( user, user.userimage, req, res );
	});
});

app.post('/api/uploaddataurl', function (req, res) {
	if(!req.body.dataURL) return utils.sendError(new Error('got no dataURL'), res);

	// incomming data:image/png;base64,iVBORw0KGgoAAAANSUh

	var base64Data = req.body.dataURL.replace(/^data:image\/png;base64,/,"");

	var name = (Date.now()) + '_webcam.png';
	var uploadedFile = path.join(ROOTDIR, config.mosaic.folders.main, name);

	require("fs").writeFile(uploadedFile, base64Data, 'base64', function (err) {
		if(err) return utils.sendError(err, res);


		renderMosaic( null, uploadedFile, req, res );
	});
});

function renderMosaic (user, userimage, req, res) {

	function renderMosaicCallbackHandler (err, mosaicimage, user) {
		if(err) return utils.sendError(err, res);

		// var testimage = 'http://onlyhdwallpapers.com/wallpaper/room_blocks_fractal_boxes_illusions_rubiks_cube_rubix_desktop_5000x5000_hd-wallpaper-227252.png';

		if(config.showDebugInfo) console.log( "Mosaic ready... sending it back to browser" );
		if(config.showDebugInfo) console.log( utils.wwwdfy(mosaicimage) );
		if(config.showDebugInfo) console.log( "Generating twitpic url" );
		twitimage.twitPicImage(mosaicimage, function (err, twiturl) {

			// dont check errors
			// if twitpic failes, the app still works
			res.send({
				mosaicimage: utils.wwwdfy(mosaicimage),
				userid: user._id,
				twitpic: (twiturl)?twiturl: config.sharing.hardcodedUrl + utils.wwwdfy(mosaicimage),
				sharing: createSharingObject(user)
			});
		});
	}

	if(!user){
		var user = {
			userimage: userimage
		}
		mongobase.saveUser(user, function (err, user) {
			if(err) return utils.sendError(err, res);

			mosaic.renderMosaic( user, renderMosaicCallbackHandler );
		});
	}else{
		mosaic.renderMosaic( user, renderMosaicCallbackHandler );
	}
}

app.get('/highquality/:userid', function (req, res) {
	if(!req.params.userid) return utils.sendError(new Error('got no user id'), res);

	res.render('highquality', {
		title: 'Hoge Kwaliteitsversie| MiX Kerstkaart 2013',
		userid: req.params.userid
	});
});

app.post('/api/renderhq', function (req, res) {
	function respondToBrowser (user) {
		if(config.showDebugInfo) console.log( user.finalOverlayHQ );
		if(config.showDebugInfo) console.log( utils.wwwdfy(user.finalOverlayHQ) );
		res.send({
			mosaicimageHQ: utils.wwwdfy(user.finalOverlayHQ),
			userid: user._id
		});
	}

	if(!req.body.userid) return utils.sendError(new Error('got no user id'), res);

	mongobase.getUser( req.body.userid, function (err, user) {
		if(err) return utils.sendError(err, res);

		// check if HQ is not already rendered:
		if(user.finalOverlayHQ){
			if(config.showDebugInfo) console.log( "Mosaic HQ already done... sending it back to browser" );

			return respondToBrowser(user);
		}else{
			mosaic.renderMosaicHQ( user, function (err, mosaicimageHQ, user) {
				if(err) return utils.sendError(err, res);
				if(config.showDebugInfo) console.log( "Mosaic HQ ready... sending it back to browser" );

				respondToBrowser(user);
			});
		}
	});
});

function getSomeRandomTilesWithPosition(nrOfTiles, callback){
	var tilesinfo = utils.getTilesInfo();

	// don't put fake tiles beyond a certain point (defined in config.js)
	var maxTilesHeigh = Math.floor(config.mosaic.greetingcard.dontPutFakeTilesBeyond / config.mosaic.tile.size);
	var maxTiles = maxTilesHeigh * tilesinfo.wide;

	mongobase.getAllTilesWithTitle(function (err, fulltiles) {
		if(err) return callback(err);

		var tiles = _.map(fulltiles, function (tile){
			return {
				title: tile.title,
				image: '/mosaic/' + tile.tileflying
			};
		});


		var possibleIndexes = [];
		for (var i = 0; i < maxTiles; i++) {
			possibleIndexes.push(i);
		};


		tiles = _.shuffle(tiles); //shuffle the tiles
		possibleIndexes = _.shuffle(possibleIndexes); // shuffle possible indexes

		tiles = tiles.slice(0, nrOfTiles);
		// add an index to each tile:
		for (var i = tiles.length - 1; i >= 0; i--) {
			tiles[i].index = possibleIndexes[i];
			tiles[i].top = utils.getTilePosition( possibleIndexes[i] ).y_px,
			tiles[i].left = utils.getTilePosition( possibleIndexes[i] ).x_px,
			tiles[i].size = config.mosaic.tile.size,
			tiles[i].maxsize = config.mosaic.flyingtile.size
		};

		callback( null, tiles );
	});
}


app.get('/sharable/:userid', function (req, res) {
	if(!req.params.userid) return utils.sendError(new Error('got no user id'), res);

	mongobase.getUser(req.params.userid, function (err, user) {
		if(err) return utils.sendError(err, res);

		res.render('sharable', {
			title: config.sharing.message +  ' | MiX Kerstkaart 2013',
			userid: req.params.userid,
			mosaicimage: utils.wwwdfy(user.finalOverlay),
			sharing: createSharingObject(user)
		});
	});
});

function createSharingObject (user) {
	var sharing = config.sharing;
	sharing.imageUrl = config.sharing.hardcodedUrl + utils.wwwdfy(user.finalOverlay);
	sharing.sharebleUrl = config.sharing.hardcodedUrl + '/sharable/' + user._id;
	return sharing;
}

function isMobile(req){
	if(!req.headers['user-agent'])
		return false;

	var md = new MobileDetect(req.headers['user-agent']);
	if( md.mobile() )
		return true;
	else
		return false;
}

